# Generated by Django 5.0.2 on 2024-03-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_customuser_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(choices=[('Fac', 'Facilitator'), ('Stu', 'Student'), ('Sta', 'Staff')], max_length=3),
        ),
    ]
