# Generated by Django 5.0.2 on 2024-03-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_interviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='url',
            field=models.URLField(default=1, max_length=550),
            preserve_default=False,
        ),
    ]
