# Generated by Django 5.0.2 on 2024-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_interviews_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='interview_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
